config/routes.rb
Rails.application.routes.draw do
  #get 'favourite_dish/index'

  get 'homepage/home'
  get 'carts/:id' => "carts#show", as: "cart"
  delete 'carts/:id' => "carts#destroy"
  root 'homepage#home'
  post 'cart_items/:id/add' => "cart_items#add_quantity", as: "cart_item_add"
  post 'cart_items/:id/reduce' => "cart_items#reduce_quantity", as: "cart_item_reduce"
  post 'cart_items' => "cart_items#create"
  get 'cart_items/:id' => "cart_items#show", as: "cart_item"
  delete 'cart_items/:id' => "cart_items#destroy"

  resources :orders
  resources :reviews

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)


  devise_for :users, controllers: { sessions: 'users/sessions' }

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
  end
  devise_for :users, skip: :all

  resources :categories do
   resources :dishes
  end
  resources :dishes
  resources :favourite_dishes
resources :users do
  resources :bookings do
    resources :dinning_tables
  end
end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  has_many :dinning_tables

  validates :occassion, presence: true
  validates :no_of_people, presence: true
  validates :date, presence: true

end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_many :dishes, through: :cart_items

  def sub_total
    sum = 0
    self.cart_items.each do |cart_item|
      sum += cart_item.total_amount
    end
    sum
  end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :dish, optional: true
  belongs_to :order, optional: true
  belongs_to :cart, optional: true

  def total_amount
    self.quantity * self.dish.price
  end

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :dishes
  def to_s
    "#{category_name}"
  end
end

app/models/dinning_table.rb
class DinningTable < ApplicationRecord
  belongs_to :booking
end

app/models/dish.rb
class Dish < ApplicationRecord
  belongs_to :category
  has_many :reviews
  has_many :cart_items
  has_one :favourite_dish


  enum status: { available: 0, unavailable: 1 }

  validates :name, presence: true
  validates :price, presence: true
  validates :description, presence: true

  def self.by_category(category_id)
    where(category: category_id)
  end

end

app/models/favourite_dish.rb
class FavouriteDish < ApplicationRecord
  belongs_to :user
  belongs_to :dish
  # validates :dish_id ,uniqueness: {scope: :user_id ,
  # message: "you have already reviewed this dish"}
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_many :dishes, through: :cart_items

  enum order_status: { ready: 0, under_process: 1 }

  validates :name, presence: true
  validates :address, presence: true
  validates :email, presence: true,format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  def total
    sum = 0
    self.cart_items.each do |cart_item|
        sum += cart_item.quantity * cart_item.dish.price
    end
    sum
  end

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :reviews
  has_many :user_products
  has_one :favourite_dish


  enum status: { available: 0, unavailable: 1 }

  validates :name, presence: true
  validates :price, presence: true
  validates :description, presence: true


end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :dish
  belongs_to :user
  validates :rating, presence:  { message: 'rating should be between 1 to 5' },numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }

end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :favourite_dishes, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_one :cart, dependent: :destroy
  has_many :orders,dependent: :destroy
  has_many :dinning_tables, through: :bookings, dependent: :destroy
  # has_many :products, through: :cart
  # has_many :products, through: :orders
  #enum role: {user: 0, admin: 1 }
  enum gender: { male: 0, female: 1, Others: 2 }
  #validates :password_digest, presence: true,
                       #length: { minimum: 6 }
  #validates :email, presence: true,format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  #validates :name, presence: true
  #validates :address, presence: true

  devise :database_authenticatable, :registerable,
     :recoverable, :rememberable, :validatable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :registerable,
  #        :recoverable, :rememberable, :validatable

  def say_hello
    "Hello World!"
 end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @user = current_user
    @booking = @user.bookings.all
  end
  def new
    @user=User.find(params[:user_id])
    @booking = @user.bookings.new
  end
  def create
    @user = User.find(params[:user_id])
    @booking = @user.bookings.build(booking_params)
    if @booking.save
      redirect_to  user_booking_path(@user,@booking)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:user_id])
    @booking = @user.bookings.find(params[:id])
  end


  private
  def booking_params
    params.require(:booking).permit(:date, :no_of_people, :occassion)
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/catagories_helper.rb
module CatagoriesHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/index.html.erb
<h1>Bookings#index</h1>
<p>Find me in app/views/bookings/index.html.erb</p>
<%= link_to 'book a table', new_user_booking_path %>
<table class="table">
  <th> Booking Number </th>
  <th>Booking Date</th>
  <th>Occasion</th>
  <th>Guest Count</th>
  <th>booked On </th>

<% @booking.each do |book| %>
    <tr class="tr">
        <td><%= book.id %></td>
        <td><%= book.date.strftime("%d/%m/%y") %></td>
        <td><%= book.occassion %></td>
        <td><%= book.no_of_people %></td>
        <td><%= book.created_at.strftime("%d/%m/%y")%></td>
    </tr>
<% end%>
</table>
<br>
<%= link_to "Back To Home Page", homepage_home_path %>

app/views/bookings/new.html.erb
<h1>new of booking</h1>
<% if @booking.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this article from being saved:</h2>

    <ul>
      <% @booking.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for [@user,@user.bookings.build]  do |form| %>
  <p>
    <%= form.label :no_of_people %><br>
    <%=  form.number_field :no_of_people %>
  </p>
  <p>
    <%= form.label :occassion %><br>
    <%= form.text_field :occassion %>
  </p>
  <p>
    <%= form.label :date %>
    <%= form.datetime_local_field :date %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %><br>

<%= link_to "Back To Home Page", homepage_home_path %>

app/views/bookings/show.html.erb
<h1>show of booking</h1>
<table>
<th>date of booking</th>
<th>occassion of booking</th>
<th>Number of Guest invited</th>
<tr>

<td><%= @booking.date.strftime("%d/%m/%y")%></td>
<td><%= @booking.occassion %></td>
<td><%= @booking.no_of_people %></td>
</table>

<%= link_to "Back To Home Page", homepage_home_path %>