config/routes.rb
Rails.application.routes.draw do
  #get 'favourite_dish/index'

  get 'homepage/home'
  get 'carts/:id' => "carts#show", as: "cart"
  delete 'carts/:id' => "carts#destroy"
  root 'homepage#home'
  post 'cart_items/:id/add' => "cart_items#add_quantity", as: "cart_item_add"
  post 'cart_items/:id/reduce' => "cart_items#reduce_quantity", as: "cart_item_reduce"
  post 'cart_items' => "cart_items#create"
  get 'cart_items/:id' => "cart_items#show", as: "cart_item"
  delete 'cart_items/:id' => "cart_items#destroy"

  resources :orders
  resources :reviews

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)


  devise_for :users, controllers: { sessions: 'users/sessions' }

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
  end
  devise_for :users, skip: :all

  resources :categories do
   resources :dishes
  end
  resources :dishes
  resources :favourite_dishes
resources :users do
  resources :bookings do
    resources :dinning_tables
  end
end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  has_many :dinning_tables

  validates :occassion, presence: true
  validates :no_of_people, presence: true
  validates :date, presence: true

end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_many :dishes, through: :cart_items

  def sub_total
    sum = 0
    self.cart_items.each do |cart_item|
      sum += cart_item.total_amount
    end
    sum
  end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :dish, optional: true
  belongs_to :order, optional: true
  belongs_to :cart, optional: true

  def total_amount
    self.quantity * self.dish.price
  end

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :dishes
  def to_s
    "#{category_name}"
  end
end

app/models/dinning_table.rb
class DinningTable < ApplicationRecord
  belongs_to :booking
end

app/models/dish.rb
class Dish < ApplicationRecord
  belongs_to :category
  has_many :reviews
  has_many :cart_items
  has_one :favourite_dish


  enum status: { available: 0, unavailable: 1 }

  validates :name, presence: true
  validates :price, presence: true
  validates :description, presence: true

  def self.by_category(category_id)
    where(category: category_id)
  end

end

app/models/favourite_dish.rb
class FavouriteDish < ApplicationRecord
  belongs_to :user
  belongs_to :dish
  # validates :dish_id ,uniqueness: {scope: :user_id ,
  # message: "you have already reviewed this dish"}
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_many :dishes, through: :cart_items

  enum order_status: { ready: 0, under_process: 1 }

  validates :name, presence: true
  validates :address, presence: true
  validates :email, presence: true,format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  def total
    sum = 0
    self.cart_items.each do |cart_item|
        sum += cart_item.quantity * cart_item.dish.price
    end
    sum
  end

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :reviews
  has_many :user_products
  has_one :favourite_dish


  enum status: { available: 0, unavailable: 1 }

  validates :name, presence: true
  validates :price, presence: true
  validates :description, presence: true


end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :dish
  belongs_to :user
  validates :rating, presence:  { message: 'rating should be between 1 to 5' },numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }

end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :favourite_dishes, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_one :cart, dependent: :destroy
  has_many :orders,dependent: :destroy
  has_many :dinning_tables, through: :bookings, dependent: :destroy
  # has_many :products, through: :cart
  # has_many :products, through: :orders
  #enum role: {user: 0, admin: 1 }
  enum gender: { male: 0, female: 1, Others: 2 }
  #validates :password_digest, presence: true,
                       #length: { minimum: 6 }
  #validates :email, presence: true,format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  #validates :name, presence: true
  #validates :address, presence: true

  devise :database_authenticatable, :registerable,
     :recoverable, :rememberable, :validatable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :registerable,
  #        :recoverable, :rememberable, :validatable

  def say_hello
    "Hello World!"
 end

end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :admin_only, except: [:index, :show]
  before_action :find_dish

  def index
    @categories = Category.all
    @dishes = Dish.where(nil)
    @dishes = @dishes.by_category(params[:category]) if params[:category].present?
  end

  def show
    @dish = Dish.find(params[:id])
  end

  private

  def find_dish
    @dish = Dish.find_by(id: params[:id])
  end

  def dish_params
    params.require(:dish).permit(:name, :price , :description, :status, :category_id, :cart_id, :order_id)
  end

end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/catagories_helper.rb
module CatagoriesHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dishes/_links.html.erb
<p><%= button_to "Add New Item", new_dish_path, method: :get %></p>

app/views/dishes/index.html.erb
<h1> index of dishes </h1>
<h3>Filter Items by Category and dishes</h3>
<%
=begin%>
 <div class="filter">
<%= form_tag("/dishes", method: "get") do %>
    <label>category</label>
    <%= select_tag "category", options_from_collection_for_select(@categories, :id, :category_name), include_blank: true %>
    <%= submit_tag "Filter"%>
<% end %>
</div>
<%
=end%>

<% @dishes.each do |dish| %>
    <div>
        <p><%= link_to dish.name, dish_path(dish) %></p>

    </div>
<% end %>

<%= link_to "Back To Home Page", homepage_home_path %>

app/views/dishes/new.html.erb
<h2>Create a New Dish</h2>
<% if @dish.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@dish.errors.count, "error") %> prohibited this article from being saved:</h2>

    <ul>
    <% @dish.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<%= form_for @dish do |f| %>

    <label>Category:</label>
    <%= f.collection_select :category_id, Category.all, :id, :category_name, include_blank: true%>
    <br>
    <label>Dish Name:</label>
    <%= f.text_field :name, class: "field_with_errors" %>
    <br>
    <%= f.label :price %>
    <%= f.number_field :price, value: number_to_currency(f.object.price.to_f, delimiter: '', unit: ''), step: :any %>
    <br>
    <%= f.label :description %>
    <%= f.text_area :description %>
    <br>
    <%= f.submit %>

<%end%>
<br>
<%= link_to "Back To Home Page", homepage_home_path %>

app/views/dishes/show.html.erb
<h1> show of dishes </h1>

<%= button_to "Back to Menu", dishes_path, method: :get %>
<h3><%= @dish.category.category_name %></h3>
<h4>Dish Name: <%= @dish.name %></h4>
<h4>Price: rs<%= @dish.price %></h4>
<p><%= @dish.description %></p>
<p><%= @dish.id %></p>
<% if user_signed_in?%>
    <%= button_to "Add to Cart", cart_items_path(dish_id: @dish.id) %>
    <%= link_to "Review Dish", new_review_path(dish_id: @dish.id), method: :get %>
    <%= link_to "Add to Favourite", new_favourite_dish_path(dish_id: @dish.id), method: :get %>
<% end %>
<br>
<%= link_to "Back To Home Page", homepage_home_path %>